[pytest]
testpaths = automation/tests
python_files = test_*.py
python_classes = Test*
python_functions = test_*
addopts = -v --html=reports/playwright_report.html --self-contained-html
base_url = http://127.0.0.1:8000
